# Generated by Django 3.2.7 on 2021-12-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_qualification1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification2', models.CharField(max_length=100)),
                ('University2', models.CharField(max_length=100)),
                ('Institution2', models.CharField(max_length=100)),
                ('Year_of_passing2', models.PositiveIntegerField()),
                ('Percentag2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification3', models.CharField(max_length=100)),
                ('University3', models.CharField(max_length=100)),
                ('Institution3', models.CharField(max_length=100)),
                ('Year_of_passing3', models.PositiveIntegerField()),
                ('Percentag3', models.CharField(max_length=100)),
            ],
        ),
    ]
