# Generated by Django 3.2.7 on 2021-12-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211211_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification1',
            old_name='Institution3',
            new_name='Institution1',
        ),
        migrations.RenameField(
            model_name='qualification1',
            old_name='Percentag3',
            new_name='Percentag1',
        ),
        migrations.RenameField(
            model_name='qualification1',
            old_name='Qualification3',
            new_name='Qualification1',
        ),
        migrations.RenameField(
            model_name='qualification1',
            old_name='University3',
            new_name='University1',
        ),
        migrations.RenameField(
            model_name='qualification1',
            old_name='Year_of_passing3',
            new_name='Year_of_passing1',
        ),
        migrations.RenameField(
            model_name='qualification3',
            old_name='Institution1',
            new_name='Institution3',
        ),
        migrations.RenameField(
            model_name='qualification3',
            old_name='Percentag1',
            new_name='Percentag3',
        ),
        migrations.RenameField(
            model_name='qualification3',
            old_name='Qualification1',
            new_name='Qualification3',
        ),
        migrations.RenameField(
            model_name='qualification3',
            old_name='University1',
            new_name='University3',
        ),
        migrations.RenameField(
            model_name='qualification3',
            old_name='Year_of_passing1',
            new_name='Year_of_passing3',
        ),
    ]
