# Generated by Django 3.2.7 on 2021-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile_no', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.PositiveIntegerField()),
                ('Education', models.CharField(max_length=100)),
                ('Upload_Documents', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
