# Generated by Django 3.2.7 on 2021-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_forms_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Mobile_no', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.PositiveIntegerField()),
                ('Education', models.CharField(max_length=100)),
                ('Upload_Documents', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
