# Generated by Django 3.2.7 on 2021-12-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211218_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='forms',
            name='Mobile_no',
            field=models.IntegerField(),
        ),
    ]
